box: generic/oracle8
#box_url: https://oracle.github.io/vagrant-projects/boxes

#Server Name
vm_name: vagrant-ansible-vmware

#Vagrant Password
vagrant_password: vagrant

mem_size: '2048'
cpus: '2'
#Number of latest octet of ip and latest three number of ssh port
ip_number: '201'

non_rotational: 'on' # SSD

network: '192.168.57.'


disk1_size: 15
disk1_device: /dev/sdb
disk1_mountpoint: '/var/lib/docker'

disk2_size: 15
disk2_device: /dev/sdc
disk2_mountpoint: '/var/lib/docker1'

disk3_size: 15
disk3_device: /dev/sdd
disk3_mountpoint: '/var/lib/docker2'

#disk4_size: 150
#disk4_device: /dev/sdb
#disk4_mountpoint: '/var/lib/docker'
